{% set name = "Cerberus" %}
{% set version = "1.3.1" %}
{% set sha256 = "0be48fc0dc84f83202a5309c0aa17cd5393e70731a1698a50d118b762fbe6875" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - cerberus
    - cerberus.tests
  commands:
    - pytest --pyargs cerberus

about:
  home: https://github.com/nicolaiarocci/cerberus
  license: ISC
  license_file: LICENSE
  summary: 'Lightweight, extensible schema and data validation tool for Python dictionaries.'

extra:
    recipe-maintainers:
        - kyleniemeyer
