travis:
  secure:
    BINSTAR_TOKEN: nyTrxf/LdLY7ikB6NdMiSA8DA/3H7p2W28OZUWYX7eBym55WqB2j5GPsv3YZCKtY689Hd5KiRM9qhAXIh9gNnNloZ2WuygFnu4NzoikZZKeMzFNZp+NMj3khte4X9m9wz+STpNCtMOFjWUVWJ0zEQsFrRN8MHBpKXkSrR/zpJDKn4P/k2fVlxHNA2r4sqHR5IHOqJjK1Z0IOXf+pRTaKbBAwfUKV1BPcwuLpAOALtZwsmykE4lRNQFj1cS7q6EXMLOahFPP9X1hwbSbpOPbO3oFSBQKqOuO+ypdvrmnyazfcqHyQN+JL+V9cXGMsH+ejOH5pwpJTRcog13F88+LVuzzGK7pSiEMGRrmLe4A9ucGoKOqxEx4F3Qd0rA6+0mCNEm0OKkK+RnuBLJtF3FsE7Uwf7PiXHoylX78BIQ51cUfvxNqPjXG5c7+BgoOzhk7PjTbwa6+GJ3RrZmS6ejmozAz+870xziUjrBCZZ+byNP0G7t5JbVM+gwM79NUsWOIsSixqxfUT1Ix2sNGJrjnXFw6MbKb06UgJqbBRNJdjnFDMB6n4OJtsDbGfzLYxJXKnhpl6m1q6xryvmjkZeO6GBUv7ahHIaS6VZsdVl1VSyv02ZU9Rd+6Zv2ACDRnjmLDKL7ogNXVoHj0x+DYLYFo/tetkKUlQV9hHYnH0QjZpSiY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
