travis:
  secure:
    BINSTAR_TOKEN: A1AH/rfoyLrO4UwW8RNcb0+fYz7yYcSHWg9MWFl2/GRqOrHmGQT9jsySpWeYi1he9F1NjhPMuUKWM2WyRMj3QHONL9WGJAe4phQTJNN8V7e2vh/MshgML2JGaxpdR1AoxY82QzF30M/SSSAnZil77DqX8p2Hh5eZ6oW0ngVN5YcWLmNSoYfLsARObSofCahuHcZkBlK877iQtsRcQrdVgpenj+pS+HS7BHInrkU643Ol61H8APRdNnVeY2PHMN3utWWu5hD/SMU0pKp43RsZI+MzJIywxa3c55PAh6FnjLmpxo4k95XJja2I+pdvXNIzCqtHOLVn2InVsfBf5EHAmphQzD3GtntZGhfwABShM1vUpvHH9XefJfaw97wFWjsjyuplLM1YInFOZIGfMSoBENTQfDpcVkIg4Z5MPBKdDOWRa9/RdXL1GXlsM91CLoSHglbKa6AIm621cu9NTTLAOmj0tZ3xp2vwUnsfraP5p5E8K8nkE0wYsaUivks1cyyZmA0G4G79UjU+PZL6Efe2thiHbioRYB+tmZHoLExUcBHN/Coe17GB1iYNfCNYGUSHOZKaTUh6wymiXUZNmWJ0Bs9IlHH0/4jd5LkEkdbPTyW8x8qXZo2adE1zg3x3RDKLL5bEq1qPLzf41yDl1mpwzmfmAJey116INcM+591spCA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
