travis:
  secure:
    BINSTAR_TOKEN: BftFC3IJ/hb0wLFcfDjRwgjN8T/nCjgaAn6jxSKq3GLgQaPUGyJkO1oTz9sZ2O2vFa77npCkaC7uQp7os8paoq1/3gwaK1kY7Ef3Hy+0Iq8Eqrmn01sAlMz6sP0TvZYhacIJZsRIgUf3lDnsFOvF5vBjllLCO2qgQEjSL2RT632qCl8Fy58TcIwDC0CiZKNHUE0A4fXJgUpSMvzRiD8AqLuhETmZLqnvozWRPZvFe7UITbNHxsDVcJNh5+b2P/rC9LQzQBmd5kABYpE9N0IWraEeXCmv1KI5wiYhLBhIeNTuC1dagdINoKfVzwEc5R/OvLqv9wGnOXeFSMi4kcbf4OrkHP9v3sYP8JJZxoPgjAw11ap8mO4mLYfVYfkRfh+17BZSoHvnU09iWpXoVCnsptHysdHuO4dHcVAuGY+arnAv6IRoZoUQoW61gPvFGU27MDQbtreUodS5lB7MjITUp7nRMpQjwcDuZTxy26F3ail+aLln58IaS/4NT7jGLMueKQ6xFa34PmyZyVLOrE30T6RknGIuZk4bilOX3F1ohRTkQvC99Lqq3bAElGMGWKsE/fYzZAUKn6FH1OG3zhBeU9wbtn4iBDGBaFTCNQ2bC9NvKjAEtm6tBJk/ZVIB+jpYlud1X8bKOe45X0zb7Oo7ZoT2Ms8Ek32Ka1cMJhUNHTQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
